// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK56TuYFUaFrLkImYRrBLAzrei1ABSKCA',
    appId: '1:321611775631:web:8ac279562dfbb0da573afa',
    messagingSenderId: '321611775631',
    projectId: 'game-todo-list',
    authDomain: 'game-todo-list.firebaseapp.com',
    storageBucket: 'game-todo-list.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWj61fGGrlMf8c21fTqJutTHB643N7yWI',
    appId: '1:321611775631:android:d0bc7ba9bee0570d573afa',
    messagingSenderId: '321611775631',
    projectId: 'game-todo-list',
    storageBucket: 'game-todo-list.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVwlDV0kQ9WxiO4ThX9spt7xT_6IQntY',
    appId: '1:321611775631:ios:808928f942b43fba573afa',
    messagingSenderId: '321611775631',
    projectId: 'game-todo-list',
    storageBucket: 'game-todo-list.firebasestorage.app',
    iosBundleId: 'com.example.gameTodoFlutter',
  );
}
